version: '3'
services:
  elastic:
    image: docker-registry.wemove.com/ingrid-elasticsearch-with-decompound:6.4.2
    environment:
      - cluster.name=ingrid
      - http.host=0.0.0.0
      - transport.host=0.0.0.0
      - http.cors.enabled=true
      - http.cors.allow-origin=*
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - xpack.security.enabled=false
      - xpack.monitoring.enabled=false
      - xpack.ml.enabled=false
    # volumes:
    #  - esdata1:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
      - 9300:9300
